### ISSUE TITLE
change github url in `setup.py`

### ISSUE THREAD

**Issue by gwarmstrong** [biocore/LabControl#561]
https://github.com/jdereus/LabControl/blob/b4ee5c60549c504a0b10c2490669c9c0dfdd970c/setup.py#L39

The `setup.py` currently uses the old url. The old url currently redirects to the new url, so it seems low priority, but I imagine it would be ideal to update this string to 'https://github.com/jdereus/labcontrol'

**Comment by charles-cowart** [comment]
Thanks! Known issue. We're waiting for ownership of LabControl to change from jdereus to biocore before changing this last bit.

**Comment by charles-cowart** [comment]
@gwarmstrong Once the project changes ownership, go ahead and submit a PR. Thanks!

**Comment by gwarmstrong** [comment]
@charles-cowart will do!

**Comment by fedarko** [comment]
Thanks George and Charlie! Just adding on here—I briefly investigated this the other day, and there are a few other places (some user-facing in the GUI) that should probably be changed (comments probably aren't super important, but the main ones are the README and HTML template files).

```bash
.../LabControl$ grep -ri "jdereus\/labman" *
labcontrol/gui/templates/sitebase.html:                  <li><a href="https://github.com/jdereus/labman/blob/master/docs/index.rst">Tutorial</a></li>
labcontrol/gui/templates/sitebase.html:        Questions? Open an issue in our <a href="https://github.com/jdereus/labman/issues">GitHub repository</a>.
labcontrol/gui/templates/error.html:  <p>Please copy the following into an issue in our <a href="https://github.com/jdereus/labman/issues" target="_blank">github repository</a></p>
labcontrol/db/process.py:                # refer to https://github.com/jdereus/labman/issues/324
labcontrol/db/process.py:                # See also: https://github.com/jdereus/labman/issues/507
README.md:git clone https://github.com/jdereus/labman.git
setup.py:      url='https://github.com/jdereus/labman',
```

**Comment by charles-cowart** [comment]
> Thanks George and Charlie! Just adding on here—I briefly investigated this the other day, and there are a few other places (some user-facing in the GUI) that should probably be changed (comments probably aren't super important, but the main ones are the README and HTML template files).
> 
> ```shell
> .../LabControl$ grep -ri "jdereus\/labman" *
> labcontrol/gui/templates/sitebase.html:                  <li><a href="https://github.com/jdereus/labman/blob/master/docs/index.rst">Tutorial</a></li>
> labcontrol/gui/templates/sitebase.html:        Questions? Open an issue in our <a href="https://github.com/jdereus/labman/issues">GitHub repository</a>.
> labcontrol/gui/templates/error.html:  <p>Please copy the following into an issue in our <a href="https://github.com/jdereus/labman/issues" target="_blank">github repository</a></p>
> labcontrol/db/process.py:                # refer to https://github.com/jdereus/labman/issues/324
> labcontrol/db/process.py:                # See also: https://github.com/jdereus/labman/issues/507
> README.md:git clone https://github.com/jdereus/labman.git
> setup.py:      url='https://github.com/jdereus/labman',
> ```

Just beat me to it! :) Yes, there's a few other places as well. In fact, if you search on dereus, there are a few more locations that should be changed:

LICENSE:Copyright (c) 2017, jdereus
README.md:git clone https://github.com/jdereus/labman.git
labcontrol/gui/templates/sitebase.html:                  <li><a href="https://github.com/jdereus/labman/blob/master/docs/index.rst">Tutorial</a></li>
labcontrol/gui/templates/sitebase.html:        Questions? Open an issue in our <a href="https://github.com/jdereus/labman/issues">GitHub repository</a>.
labcontrol/gui/templates/error.html:  <p>Please copy the following into an issue in our <a href="https://github.com/jdereus/labman/issues" target="_blank">github repository</a></p>
labcontrol/db/sheet.py:                # refer to https://github.com/jdereus/labman/issues/324
labcontrol/db/sheet.py:                # See also: https://github.com/jdereus/labman/issues/507
labcontrol.egg-info/PKG-INFO:Home-page: https://github.com/jdereus/labman
labcontrol.egg-info/PKG-INFO:Author-email: jdereus@ucsd.edu
labcontrol.egg-info/PKG-INFO:        git clone https://github.com/jdereus/labman.git
setup.py:      author_email='jdereus@ucsd.edu',
setup.py:      url='https://github.com/jdereus/labman',

I have to do some investigation regarding copyright and authorship, but the GitHub location can be changed once the ownership of the repo moves to biocore.. Will update this issue as we get more word on copyright.
