### ISSUE TITLE
flake8 does not check labcontrol directory

### ISSUE THREAD

**Issue by gwarmstrong** [biocore/LabControl#586]
https://github.com/biocore/LabControl/blob/1427ad163682ff11b1086e0e3b1010ba1a2166ee/.travis.yml#L100

This line has `labman` instead of `labcontrol` and flake8 does not throw non-zero exit codes if it is passed directories/files that do not exists. So this should be changed to `labcontrol` so the python code is actually linted.

**Comment by fedarko** [comment]
This is a good catch, thanks!
